///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Outputs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OutputsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("751869b6-9822-4c6e-9498-0703eadb8e84")]
    public partial class OutputsRepository : RepoGenBaseFolder
    {
        static OutputsRepository instance = new OutputsRepository();
        OutputsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        OutputsRepositoryFolders.OpenSnapXRoutineAppFolder _opensnapxroutine;
        OutputsRepositoryFolders.StatisticSTANotepadAppFolder _statisticstanotepad;
        OutputsRepositoryFolders.ReportStaNotepadAppFolder _reportstanotepad;
        OutputsRepositoryFolders.PrintPRTNotepadAppFolder _printprtnotepad;
        OutputsRepositoryFolders.ExportStaNotepadAppFolder _exportstanotepad;
        OutputsRepositoryFolders.DatastreamDatNotepadAppFolder _datastreamdatnotepad;

        /// <summary>
        /// Gets the singleton class instance representing the OutputsRepository element repository.
        /// </summary>
        [RepositoryFolder("751869b6-9822-4c6e-9498-0703eadb8e84")]
        public static OutputsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OutputsRepository() 
            : base("OutputsRepository", "/", null, 0, false, "751869b6-9822-4c6e-9498-0703eadb8e84", ".\\RepositoryImages\\OutputsRepository751869b6.rximgres")
        {
            _snapxuntitled = new OutputsRepositoryFolders.SnapXUntitledAppFolder(this);
            _opensnapxroutine = new OutputsRepositoryFolders.OpenSnapXRoutineAppFolder(this);
            _statisticstanotepad = new OutputsRepositoryFolders.StatisticSTANotepadAppFolder(this);
            _reportstanotepad = new OutputsRepositoryFolders.ReportStaNotepadAppFolder(this);
            _printprtnotepad = new OutputsRepositoryFolders.PrintPRTNotepadAppFolder(this);
            _exportstanotepad = new OutputsRepositoryFolders.ExportStaNotepadAppFolder(this);
            _datastreamdatnotepad = new OutputsRepositoryFolders.DatastreamDatNotepadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("751869b6-9822-4c6e-9498-0703eadb8e84")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("43775787-6981-45c9-a854-418cd535d936")]
        public virtual OutputsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The OpenSnapXRoutine folder.
        /// </summary>
        [RepositoryFolder("049be60f-5b9d-41ef-833c-468f15aa4077")]
        public virtual OutputsRepositoryFolders.OpenSnapXRoutineAppFolder OpenSnapXRoutine
        {
            get { return _opensnapxroutine; }
        }

        /// <summary>
        /// The StatisticSTANotepad folder.
        /// </summary>
        [RepositoryFolder("9b8033e3-2ed6-41f3-9e88-daefd145b3ce")]
        public virtual OutputsRepositoryFolders.StatisticSTANotepadAppFolder StatisticSTANotepad
        {
            get { return _statisticstanotepad; }
        }

        /// <summary>
        /// The ReportStaNotepad folder.
        /// </summary>
        [RepositoryFolder("950330e5-038b-43c1-a217-a23cbf6163c0")]
        public virtual OutputsRepositoryFolders.ReportStaNotepadAppFolder ReportStaNotepad
        {
            get { return _reportstanotepad; }
        }

        /// <summary>
        /// The PrintPRTNotepad folder.
        /// </summary>
        [RepositoryFolder("c0b53c29-718d-473c-aad2-980d5c9449e1")]
        public virtual OutputsRepositoryFolders.PrintPRTNotepadAppFolder PrintPRTNotepad
        {
            get { return _printprtnotepad; }
        }

        /// <summary>
        /// The ExportStaNotepad folder.
        /// </summary>
        [RepositoryFolder("00eece80-a99d-429d-a91c-98bee5f41fc2")]
        public virtual OutputsRepositoryFolders.ExportStaNotepadAppFolder ExportStaNotepad
        {
            get { return _exportstanotepad; }
        }

        /// <summary>
        /// The DatastreamDatNotepad folder.
        /// </summary>
        [RepositoryFolder("11c49540-7e7b-4431-8773-15d87943d08f")]
        public virtual OutputsRepositoryFolders.DatastreamDatNotepadAppFolder DatastreamDatNotepad
        {
            get { return _datastreamdatnotepad; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class OutputsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("43775787-6981-45c9-a854-418cd535d936")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snapxuntitledInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _buttonnewInfo;
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "43775787-6981-45c9-a854-418cd535d936", "")
            {
                _snapxuntitledInfo = new RepoItemInfo(this, "SnapXUntitled", "titlebar[@accessiblerole='TitleBar']", 30000, null, "7b7d79bf-1f6c-4f0c-83e2-7d402f427298");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container/form//button[@text='&OK' and @controlid='1148']", 30000, null, "ad493450-7358-4e88-830e-9afd6077d9fe");
                _buttonnewInfo = new RepoItemInfo(this, "ButtonNew", "container/form//container/toolbar/button[@text='New' and @commandid='57600']", 30000, null, "d48bb46b-36b4-4c9a-888a-d279e78e587c");
                _finishInfo = new RepoItemInfo(this, "Finish", "container/form/?/?/element/element/container/button[@text='Finish' and @controlid='3165']", 30000, null, "79f81ad0-67e4-4979-afb8-84862a366df3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("43775787-6981-45c9-a854-418cd535d936")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("43775787-6981-45c9-a854-418cd535d936")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnapXUntitled item.
            /// </summary>
            [RepositoryItem("7b7d79bf-1f6c-4f0c-83e2-7d402f427298")]
            public virtual Ranorex.TitleBar SnapXUntitled
            {
                get
                {
                    return _snapxuntitledInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The SnapXUntitled item info.
            /// </summary>
            [RepositoryItemInfo("7b7d79bf-1f6c-4f0c-83e2-7d402f427298")]
            public virtual RepoItemInfo SnapXUntitledInfo
            {
                get
                {
                    return _snapxuntitledInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("ad493450-7358-4e88-830e-9afd6077d9fe")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("ad493450-7358-4e88-830e-9afd6077d9fe")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ButtonNew item.
            /// </summary>
            [RepositoryItem("d48bb46b-36b4-4c9a-888a-d279e78e587c")]
            public virtual Ranorex.Button ButtonNew
            {
                get
                {
                    return _buttonnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNew item info.
            /// </summary>
            [RepositoryItemInfo("d48bb46b-36b4-4c9a-888a-d279e78e587c")]
            public virtual RepoItemInfo ButtonNewInfo
            {
                get
                {
                    return _buttonnewInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("79f81ad0-67e4-4979-afb8-84862a366df3")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("79f81ad0-67e4-4979-afb8-84862a366df3")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

        /// <summary>
        /// The OpenSnapXRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("049be60f-5b9d-41ef-833c-468f15aa4077")]
        public partial class OpenSnapXRoutineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1148Info;

            /// <summary>
            /// Creates a new OpenSnapXRoutine  folder.
            /// </summary>
            public OpenSnapXRoutineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenSnapXRoutine", "/form[@title='Open Snap-X Routine']", parentFolder, 30000, null, true, "049be60f-5b9d-41ef-833c-468f15aa4077", "")
            {
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", 30000, null, "c0adf465-8939-4d95-836f-192dfd9f4d69");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("049be60f-5b9d-41ef-833c-468f15aa4077")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("049be60f-5b9d-41ef-833c-468f15aa4077")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("c0adf465-8939-4d95-836f-192dfd9f4d69")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("c0adf465-8939-4d95-836f-192dfd9f4d69")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }
        }

        /// <summary>
        /// The StatisticSTANotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("9b8033e3-2ed6-41f3-9e88-daefd145b3ce")]
        public partial class StatisticSTANotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new StatisticSTANotepad  folder.
            /// </summary>
            public StatisticSTANotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StatisticSTANotepad", "/form[@title='statistic.STA - Notepad']", parentFolder, 30000, null, true, "9b8033e3-2ed6-41f3-9e88-daefd145b3ce", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "38f2a400-a4e9-43f1-93ec-00e22f4b56d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9b8033e3-2ed6-41f3-9e88-daefd145b3ce")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9b8033e3-2ed6-41f3-9e88-daefd145b3ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("38f2a400-a4e9-43f1-93ec-00e22f4b56d5")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("38f2a400-a4e9-43f1-93ec-00e22f4b56d5")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The ReportStaNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("950330e5-038b-43c1-a217-a23cbf6163c0")]
        public partial class ReportStaNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ReportStaNotepad  folder.
            /// </summary>
            public ReportStaNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReportStaNotepad", "/form[@title='report.sta - Notepad']", parentFolder, 30000, null, true, "950330e5-038b-43c1-a217-a23cbf6163c0", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "1cdc580d-4a90-46c4-acad-7e5348bf4e85");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("950330e5-038b-43c1-a217-a23cbf6163c0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("950330e5-038b-43c1-a217-a23cbf6163c0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("1cdc580d-4a90-46c4-acad-7e5348bf4e85")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("1cdc580d-4a90-46c4-acad-7e5348bf4e85")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The PrintPRTNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("c0b53c29-718d-473c-aad2-980d5c9449e1")]
        public partial class PrintPRTNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new PrintPRTNotepad  folder.
            /// </summary>
            public PrintPRTNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PrintPRTNotepad", "/form[@title='print.PRT - Notepad']", parentFolder, 30000, null, true, "c0b53c29-718d-473c-aad2-980d5c9449e1", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "a7ca3844-b299-4b2b-bb9f-d972f349774d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0b53c29-718d-473c-aad2-980d5c9449e1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0b53c29-718d-473c-aad2-980d5c9449e1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("a7ca3844-b299-4b2b-bb9f-d972f349774d")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("a7ca3844-b299-4b2b-bb9f-d972f349774d")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The ExportStaNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("00eece80-a99d-429d-a91c-98bee5f41fc2")]
        public partial class ExportStaNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ExportStaNotepad  folder.
            /// </summary>
            public ExportStaNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExportStaNotepad", "/form[@title='export.sta - Notepad']", parentFolder, 30000, null, true, "00eece80-a99d-429d-a91c-98bee5f41fc2", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "c5579505-602f-4ac1-b0ba-cb08c68a4d03");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00eece80-a99d-429d-a91c-98bee5f41fc2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00eece80-a99d-429d-a91c-98bee5f41fc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("c5579505-602f-4ac1-b0ba-cb08c68a4d03")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("c5579505-602f-4ac1-b0ba-cb08c68a4d03")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The DatastreamDatNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("11c49540-7e7b-4431-8773-15d87943d08f")]
        public partial class DatastreamDatNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new DatastreamDatNotepad  folder.
            /// </summary>
            public DatastreamDatNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DatastreamDatNotepad", "/form[@title='datastream.dat - Notepad']", parentFolder, 30000, null, true, "11c49540-7e7b-4431-8773-15d87943d08f", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "a0701b51-574a-4b79-80e2-b20b683493a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("11c49540-7e7b-4431-8773-15d87943d08f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("11c49540-7e7b-4431-8773-15d87943d08f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("a0701b51-574a-4b79-80e2-b20b683493a8")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("a0701b51-574a-4b79-80e2-b20b683493a8")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

    }
#pragma warning restore 0436
}